export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

//forum
export const GET_FORUMS = "GET_FORUMS";
export const GET_FORUMS_SUCCESS = "GET_FORUMS_SUCCESS";
export const GET_FORUMS_FAIL = "GET_FORUMS_FAIL";
export const GET_ONE_FORUM = "GET_ONE_FORUM";
export const GET_ONE_FORUM_SUCCESS = "GET_ONE_FORUM_SUCCESS";
export const GET_ONE_FORUM_FAIL = "GET_ONE_FORUM_FAIL";

//discussion
export const GET_DISCUSSIONS = "GET_DISCUSSIONS";
export const GET_DISCUSSIONS_SUCCESS = "GET_DISCUSSIONS_SUCCESS";
export const GET_DISCUSSIONS_FAIL = "GET_DISCUSSIONS_FAIL";
export const CREATE_DISCUSSION = "CREATE_DISCUSSION";
export const CREATE_DISCUSSION_SUCCESS = "CREATE_DISCUSSION_SUCCESS";
export const CREATE_DISCUSSION_FAIL = "CREATE_DISCUSSION_FAIL";
export const GET_ONE_DISCUSSION = "GET_ONE_DISCUSSION";
export const GET_ONE_DISCUSSION_SUCCESS = "GET_ONE_DISCUSSION_SUCCESS";
export const GET_ONE_DISCUSSION_FAIL = "GET_ONE_DISCUSSION_FAIL";

//reply
export const GET_REPLIES = "GET_REPLIES";
export const GET_REPLIES_SUCCESS = "GET_REPLIES_SUCCESS";
export const GET_REPLIES_FAIL = "GET_REPLIES_FAIL";

//input change
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
